### ISSUE TITLE
latexrun fails with a warning about 'NoneType' not having a 'startswith' attribute

### ISSUE THREAD

**Issue by kozross** [aclements/latexrun#51]
The error, with the ``--debug`` flag, is

```
loading database
hashing /usr/share/texmf-dist/tex/latex/amsmath/amsgen.sty
hashing /usr/share/texmf-dist/tex/latex/oberdiek/auxhook.sty
hashing /usr/share/texmf-dist/fonts/map/fontname/texfonts.map
hashing /usr/share/texmf-dist/fonts/tfm/public/amsfonts/cmextra/cmex8.tfm
hashing /usr/share/texmf-dist/fonts/tfm/public/cm/cmr12.tfm
hashing /usr/share/texmf-dist/tex/latex/hyperref/hpdftex.def
hashing /usr/share/texmf-dist/tex/latex/base/article.cls
hashing /usr/share/texmf-dist/web2c/texmf.cnf
hashing /usr/share/texmf-dist/fonts/tfm/public/cm/cmr8.tfm
hashing /usr/share/texmf-dist/fonts/tfm/public/cm/cmmi8.tfm
hashing /usr/share/texmf-dist/tex/generic/oberdiek/gettitlestring.sty
hashing /usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmmi10.pfb
hashing /usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy10.pfb
hashing /usr/share/texmf-dist/fonts/tfm/public/amsfonts/symbols/msbm10.tfm
hashing /usr/share/texmf-dist/fonts/tfm/public/cm/cmmi12.tfm
hashing /usr/share/texmf-dist/tex/latex/url/url.sty
hashing /usr/share/texmf-dist/tex/latex/amsmath/amsopn.sty
hashing /usr/share/texmf-dist/tex/latex/amsmath/amsmath.sty
hashing /usr/share/texmf-dist/tex/latex/booktabs/booktabs.sty
hashing /usr/share/texmf-dist/tex/latex/hyperref/nameref.sty
hashing /usr/share/texmf-dist/fonts/tfm/public/amsfonts/cmextra/cmex7.tfm
hashing /usr/share/texmf-dist/fonts/tfm/public/amsfonts/symbols/msam10.tfm
hashing /usr/share/texmf-dist/fonts/tfm/public/cm/cmex10.tfm
hashing /usr/share/texmf-dist/fonts/tfm/public/amsfonts/symbols/msam7.tfm
hashing /usr/share/texmf-dist/tex/latex/hyperref/pd1enc.def
hashing /usr/share/texmf-dist/fonts/tfm/public/cm/cmbx10.tfm
hashing memetic.tex
hashing /usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmti10.pfb
hashing /usr/share/texmf-dist/fonts/tfm/public/cm/cmsy10.tfm
hashing /usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmbx12.pfb
hashing /usr/share/texmf-dist/tex/latex/amsfonts/umsb.fd
hashing /usr/share/texmf-dist/tex/latex/ntgclass/a4.sty
hashing /usr/share/texmf-dist/fonts/tfm/public/cm/cmr6.tfm
hashing /usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmr12.pfb
hashing /usr/share/texmf-dist/tex/latex/amsfonts/amssymb.sty
hashing /usr/share/texmf-dist/tex/latex/amscls/amsthm.sty
hashing /usr/share/texmf-dist/fonts/tfm/public/cm/cmbx12.tfm
hashing /usr/share/texmf-dist/fonts/tfm/public/cm/cmsy6.tfm
hashing /usr/share/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty
hashing /usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb
hashing /var/lib/texmf/web2c/pdftex/pdflatex.fmt
hashing /usr/share/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
hashing latex.out/memetic.aux
task latex::memetic.tex: unstable (changed: file('latex.out/memetic.aux',))
task latex::memetic.tex: pre-hashing latex.out/memetic.log
hashing latex.out/memetic.log
task latex::memetic.tex: pre-hashing latex.out/memetic.aux
task latex::memetic.tex: pre-hashing latex.out/memetic.out
hashing latex.out/memetic.out
task latex::memetic.tex: pre-hashing latex.out/memetic.pdf
hashing latex.out/memetic.pdf
task latex::memetic.tex: pre-hashing latex.out/memetic.fls
hashing latex.out/memetic.fls
task latex::memetic.tex: running
running ['pdflatex', '-interaction', 'nonstopmode', '-recorder', '-output-directory', 'latex.out', 'memetic.tex']
hashing /usr/share/texmf-dist/tex/latex/base/omscmr.fd
hashing /usr/share/texmf-dist/tex/latex/oberdiek/kvoptions.sty
hashing /usr/share/texmf-dist/tex/latex/hyperref/hyperref.sty
hashing /usr/share/texmf-dist/fonts/tfm/public/cm/cmmi6.tfm
hashing /usr/share/texmf-dist/fonts/tfm/public/cm/cmti10.tfm
hashing /usr/share/texmf-dist/fonts/tfm/public/cm/cmr17.tfm
hashing /usr/share/texmf-dist/tex/latex/graphics/keyval.sty
hashing /usr/share/texmf-dist/tex/latex/amsmath/amstext.sty
hashing /usr/share/texmf-dist/tex/latex/base/size10.clo
hashing /usr/share/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty
hashing /usr/share/texmf-dist/tex/latex/amsmath/amsbsy.sty
hashing /usr/share/texmf-dist/tex/latex/amsfonts/amsfonts.sty
hashing /usr/share/texmf-dist/tex/latex/amsfonts/umsa.fd
hashing /usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmbx10.pfb
hashing /usr/share/texmf-dist/fonts/tfm/public/amsfonts/symbols/msbm5.tfm
hashing /usr/share/texmf-dist/tex/latex/a4wide/a4wide.sty
hashing /var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map
hashing /usr/share/texmf-dist/fonts/tfm/public/amsfonts/symbols/msam5.tfm
hashing /usr/share/texmf-dist/tex/latex/latexconfig/hyperref.cfg
hashing /usr/share/texmf-dist/fonts/tfm/public/amsfonts/symbols/msbm7.tfm
hashing /usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmr17.pfb
hashing latex.out/memetic.bbl
hashing /usr/share/texmf-dist/tex/generic/ifxetex/ifxetex.sty
hashing /usr/share/texmf-dist/fonts/tfm/public/cm/cmsy8.tfm
hashing latex.out/memetic.pdf
hashing latex.out/memetic.log
hashing latex.out/memetic.fls
hashing latex.out/memetic.out
hashing latex.out/memetic.aux
committing database
task latex_commit::memetic.tex: unstable (changed: latex())
task latex_commit::memetic.tex: pre-hashing memetic.pdf
hashing memetic.pdf
task latex_commit::memetic.tex: running
commiting latex.out/memetic.pdf to memetic.pdf
hashing memetic.pdf
committing database
scanning for bib commands in latex.out/memetic.aux
task bibtex::memetic.tex: unstable (changed: never run)
task bibtex::memetic.tex: running
running ['bibtex', 'memetic.aux'] in latex.out
Traceback (most recent call last):
  File "/usr/bin/latexrun", line 1936, in <module>
    main()
  File "/usr/bin/latexrun", line 169, in main
    stable = run_tasks(tasks, args.max_iterations)
  File "/usr/bin/latexrun", line 524, in run_tasks
    task.run()
  File "/usr/bin/latexrun", line 621, in run
    result = self._execute()
  File "/usr/bin/latexrun", line 1614, in _execute
    inputs, auxnames, outbase = self.__parse_inputs(stdout, cwd, env)
  File "/usr/bin/latexrun", line 1686, in __parse_inputs
    if filename.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

This appears to be triggered by use of BibTeX - this didn't happen to me when I didn't need to use it.

**Comment by bagrow** [comment]
Can confirm. I fixed it by using `\bibliography{main}` instead of `\bibliography{main.bib}` (for example). The latter leads to latexrun looking for a file `main.bib.bib`.
